-dontwarn com.facebook.imagepipeline.nativecode.WebpTranscoder
-keep class com.facebook.imagepipeline.nativecode.WebpTranscoder { *; }
-keep class com.facebook.imagepipeline.nativecode.WebpTranscoderImpl { *; }
