name: instason
description: Instagram benzeri sosyal medya uygulaması
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.24.5
  get: ^4.6.5
  audioplayers: ^6.3.0
  flutter_screenutil: ^5.9.3
  
  _flutterfire_internals: ^1.3.53
  args: ^2.6.0
  async: ^2.12.0
  cached_network_image: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  cached_network_image_web: ^1.3.1
  chewie: ^1.10.0
  cloud_firestore: ^5.6.5
  cloud_firestore_platform_interface: ^6.6.5
  cloud_firestore_web: ^4.4.5
  connectivity_plus: ^6.1.3
  connectivity_plus_platform_interface: ^2.0.1
  cross_file: ^0.3.4+2
  crypto: ^3.0.6
  csslib: ^1.0.2
  dbus: ^0.7.11
  fake_async: ^1.3.2
  ffi: ^2.1.4
  file: ^7.0.1
  file_selector_linux: ^0.9.3+2
  file_selector_macos: ^0.9.4+2
  file_selector_platform_interface: ^2.6.2
  file_selector_windows: ^0.9.3+4
  firebase_app_check: ^0.3.2+4
  firebase_app_check_platform_interface: ^0.1.1+4
  firebase_app_check_web: ^0.2.0+8
  firebase_auth: ^5.5.1
  firebase_auth_platform_interface: ^7.6.1
  firebase_auth_web: ^5.14.1
  firebase_core: ^3.12.1
  firebase_core_platform_interface: ^5.4.0
  firebase_core_web: ^2.21.1
  firebase_messaging: ^15.2.4
  firebase_messaging_platform_interface: ^4.6.4
  firebase_messaging_web: ^3.10.4
  firebase_storage: ^12.4.4
  firebase_storage_platform_interface: ^5.2.4
  firebase_storage_web: ^3.10.11
  fixnum: ^1.1.1
  flutter_cache_manager: ^3.4.1
  flutter_image_compress: ^2.4.0
  flutter_image_compress_common: ^1.0.6
  flutter_image_compress_macos: ^1.0.3
  flutter_image_compress_ohos: ^0.0.3
  flutter_image_compress_platform_interface: ^1.0.5
  flutter_image_compress_web: ^0.1.5
  flutter_local_notifications: ^18.0.1
  flutter_local_notifications_linux: ^5.0.0
  flutter_local_notifications_platform_interface: ^8.0.0
  flutter_plugin_android_lifecycle: ^2.0.27
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  html: ^0.15.5
  http: ^1.3.0
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  image_picker_android: ^0.8.12+21
  image_picker_for_web: ^3.0.6
  image_picker_ios: ^0.8.12+2
  image_picker_linux: ^0.2.1+1
  image_picker_macos: ^0.2.1+2
  image_picker_platform_interface: ^2.10.1
  image_picker_windows: ^0.2.1+1
  intl: ^0.19.0
  js: ^0.7.2
  leak_tracker: ^10.0.8
  lints: ^5.1.1
  material_color_utilities: ^0.11.1
  mime: ^2.0.0
  nested: ^1.0.0
  nm: ^0.5.0
  octo_image: ^2.1.0
  package_info_plus: ^8.3.0
  package_info_plus_platform_interface: ^3.2.0
  path_parsing: ^1.1.0
  path_provider: ^2.1.5
  path_provider_android: ^2.2.15
  path_provider_foundation: ^2.4.1
  path_provider_linux: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  path_provider_windows: ^2.3.0
  permission_handler: ^11.4.0
  permission_handler_android: ^12.1.0
  permission_handler_apple: ^9.4.6
  permission_handler_html: ^0.1.3+5
  permission_handler_platform_interface: ^4.3.0
  permission_handler_windows: ^0.2.1
  petitparser: ^6.1.0
  photo_view: ^0.15.0
  platform: ^3.1.6
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  rxdart: ^0.27.7
  share_plus: ^10.1.4
  share_plus_platform_interface: ^5.0.2
  shared_preferences: ^2.5.2
  shared_preferences_android: ^2.4.6
  shared_preferences_foundation: ^2.5.4
  shared_preferences_linux: ^2.4.1
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.4.3
  shared_preferences_windows: ^2.4.1
  sprintf: ^7.0.0
  sqflite: ^2.4.2
  sqflite_android: ^2.4.1
  sqflite_common: ^2.5.5
  sqflite_darwin: ^2.4.2
  sqflite_platform_interface: ^2.4.0
  story_view: ^0.16.3
  synchronized: ^3.3.1
  timeago: ^3.7.0
  timezone: ^0.10.0
  typed_data: ^1.4.0
  url_launcher: ^6.3.1
  url_launcher_android: ^6.3.14
  url_launcher_ios: ^6.3.2
  url_launcher_linux: ^3.2.1
  url_launcher_macos: ^3.2.2
  url_launcher_platform_interface: ^2.3.2
  url_launcher_web: ^2.4.0
  url_launcher_windows: ^3.1.4
  uuid: ^4.5.1
  vector_graphics: ^1.1.18
  vector_graphics_codec: ^1.1.13
  vector_graphics_compiler: ^1.1.16
  video_player: ^2.9.3
  video_player_android: ^2.7.17
  video_player_avfoundation: ^2.7.0
  video_player_platform_interface: ^6.3.0
  video_player_web: ^2.3.4
  wakelock_plus: ^1.2.10
  wakelock_plus_platform_interface: ^1.2.2
  web: ^1.1.1
  win32: ^5.11.0
  xdg_directories: ^1.1.0
  xml: ^6.5.0
  record: ^5.2.1
  flutter_webrtc: ^0.12.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  
